
name: Test

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  # This workflow contains a single job called "build"
  pytest:

    runs-on: ubuntu-latest
        
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' 
          architecture: 'x64' 
      
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install pyboolnet
        run: python setup.py install

      - name: Install libreadline-dev
        run: sudo apt-get install -qqy libreadline-dev

      - name: Symlink libreadline8 to libreadline6
        run: |
          cd /lib/x86_64-linux-gnu
          sudo ln -s libreadline.so.8.0 libreadline.so.6

      - name: Install imagemagick and graphviz
        run: |
          sudo apt install graphviz
          sudo apt install imagemagick

      - name: Test with pytest
        run: |
          cd /home/runner/work/pyboolnet/pyboolnet/
          pytest

